spring.application.name=performanceTesting
debug=true
spring.threads.virtual.enabled=true

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/performance_test
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms

# PostgreSQL + Hibernate ORM (JPA)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
